/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistasControladores;

import Modelos.Cubiculo;
import Modelos.Taller;
import Modelos.Tecnico;
import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pipet
 */
public class InterfazGrafica extends javax.swing.JFrame {

    Taller miTaller;

    public InterfazGrafica() {
        initComponents();
        //this.miTaller = new Taller("a1", "El Cacharro", "La 23");

        cargarSesion();
        actualizarComboCubiculos();
        actualizarTablaTecnicos();

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {

                eventoCierre();
            }
        });

    }

    public void eventoCierre() {
        System.out.println("Guardando");
        try {
            ObjectOutputStream salida = new ObjectOutputStream(new FileOutputStream("taller.obj"));
            salida.writeObject(this.miTaller);
            salida.close();
        } catch (Exception ex) {
            System.out.println("" + ex);
        }
        System.exit(0);
    }

    public void cargarSesion() {
        try {
            ObjectInputStream entrada = new ObjectInputStream(new FileInputStream("taller.obj"));
            this.miTaller = (Taller) entrada.readObject();
        } catch (Exception ex) {
            System.out.println("" + ex);
        }
    }

    public void guardarArchivo(String contenido, String extension) {
        try {
            JFileChooser file = new JFileChooser();
            file.showSaveDialog(this);
            //String ruta = "" + file.getCurrentDirectory();
            try (BufferedWriter save = new BufferedWriter(new FileWriter(file.getSelectedFile().toString() + "." + extension))) {
                save.write(contenido);
            }
            JOptionPane.showMessageDialog(null, "El archivo se a guardado Exitosamente",
                    "Información",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Su archivo no se ha guardado",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
        }
    }

    public void actualizarTablaTecnicos() {
        String nombresColumnas[] = {"Cedula", "Nombre", "Telefono", "Años Experiencia", "Especializacion"};
        DefaultTableModel miModelo = new DefaultTableModel(null, nombresColumnas);
        this.tblTecnicos.setModel(miModelo);
        for (Tecnico actual : this.miTaller.getMisTecnicos()) {
            String fila[] = new String[nombresColumnas.length];
            fila[0] = actual.getCedula();
            fila[1] = actual.getNombre();
            fila[2] = actual.getTelefono();
            fila[3] = "" + actual.getAñosExperiencia();
            fila[4] = actual.getEspecializacion();
            miModelo.addRow(fila);
        }
    }

    public void actualizarTablaRelacionTecnicosCubiculos(String cedula) {
        String nombresColumnas[] = {"Id", "Nombre"};
        DefaultTableModel miModelo = new DefaultTableModel(null, nombresColumnas);
        this.tblRelacionTecnicoCubiculo.setModel(miModelo);
        Tecnico encotrado = this.miTaller.buscarTecnico(cedula);
        if (encotrado != null) {
            for (Cubiculo cubiculoActual : encotrado.getMisCubiculos()) {
                String fila[] = new String[nombresColumnas.length];
                fila[0] = cubiculoActual.getId();
                fila[1] = cubiculoActual.getNombre();
                miModelo.addRow(fila);
            }
        }

    }

    public void actualizarComboCubiculos() {
        this.cbCubiculosTecnico.removeAllItems();
        for (Cubiculo actual : this.miTaller.getMisCubiculos()) {
            cbCubiculosTecnico.addItem(actual.getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCedulaPersona = new javax.swing.JTextField();
        txtNombrePersona = new javax.swing.JTextField();
        txtExperienciaTecnico = new javax.swing.JTextField();
        txtTelefonoPersona = new javax.swing.JTextField();
        txtEspecialidadTecnico = new javax.swing.JTextField();
        btnCrearPersona = new javax.swing.JButton();
        btnBuscarPersona = new javax.swing.JButton();
        btnEditarPersona = new javax.swing.JButton();
        btnEliminarPersona = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cbCubiculosTecnico = new javax.swing.JComboBox<>();
        btnAgregarRelacionCubiculo = new javax.swing.JButton();
        btnEliminarRelacionCubiculo = new javax.swing.JButton();
        btnCertificadoTecnico = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTecnicos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRelacionTecnicoCubiculo = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIdCubiculo = new javax.swing.JTextField();
        txtNombreCubiculo = new javax.swing.JTextField();
        btnCrearCubiculo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cedula:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Teléfono");

        jLabel5.setText("Años de experiencia:");

        jLabel6.setText("Especialidad:");

        txtTelefonoPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoPersonaActionPerformed(evt);
            }
        });

        btnCrearPersona.setText("Crear");
        btnCrearPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPersonaActionPerformed(evt);
            }
        });

        btnBuscarPersona.setText("Buscar");
        btnBuscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPersonaActionPerformed(evt);
            }
        });

        btnEditarPersona.setText("Editar");
        btnEditarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPersonaActionPerformed(evt);
            }
        });

        btnEliminarPersona.setText("Eliminar");
        btnEliminarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPersonaActionPerformed(evt);
            }
        });

        jLabel10.setText("Cubiculos");

        cbCubiculosTecnico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAgregarRelacionCubiculo.setText("Agregar");
        btnAgregarRelacionCubiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRelacionCubiculoActionPerformed(evt);
            }
        });

        btnEliminarRelacionCubiculo.setText("Eliminar");
        btnEliminarRelacionCubiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarRelacionCubiculoActionPerformed(evt);
            }
        });

        btnCertificadoTecnico.setText("Certificado");
        btnCertificadoTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCertificadoTecnicoActionPerformed(evt);
            }
        });

        jButton1.setText("Lista");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblTecnicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTecnicos);

        tblRelacionTecnicoCubiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblRelacionTecnicoCubiculo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEspecialidadTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtExperienciaTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCedulaPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefonoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCrearPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnBuscarPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbCubiculosTecnico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnEditarPersona)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarPersona))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAgregarRelacionCubiculo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminarRelacionCubiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCertificadoTecnico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCedulaPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTelefonoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtExperienciaTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtEspecialidadTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCrearPersona)
                            .addComponent(btnBuscarPersona)
                            .addComponent(btnEditarPersona)
                            .addComponent(btnEliminarPersona))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cbCubiculosTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarRelacionCubiculo)
                            .addComponent(btnEliminarRelacionCubiculo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCertificadoTecnico)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(280, 280, 280))))
        );

        jTabbedPane1.addTab("Tecnicos", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 934, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Vehículos", jPanel2);

        jLabel8.setText("Id");

        jLabel9.setText("Nombre");

        btnCrearCubiculo.setText("Crear");
        btnCrearCubiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCubiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearCubiculo)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdCubiculo)
                            .addComponent(txtNombreCubiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))))
                .addContainerGap(718, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtIdCubiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNombreCubiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnCrearCubiculo)
                .addContainerGap(401, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cubículos", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void limpiarCajas() {
        this.txtCedulaPersona.setText("");
        this.txtEspecialidadTecnico.setText("");
        this.txtExperienciaTecnico.setText("");

        this.txtNombrePersona.setText("");
        this.txtTelefonoPersona.setText("");
        this.txtIdCubiculo.setText("");
        this.txtNombreCubiculo.setText("");
    }
    private void txtTelefonoPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoPersonaActionPerformed

    private void btnCrearPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPersonaActionPerformed
        String cedula = this.txtCedulaPersona.getText();
        String nombre = this.txtNombrePersona.getText();
        String telefono = this.txtTelefonoPersona.getText();
        int añosExperiencia = Integer.parseInt(this.txtExperienciaTecnico.getText());
        String especialidad = this.txtEspecialidadTecnico.getText();
        this.miTaller.crearTecnico(cedula,
                nombre,
                telefono,
                especialidad,
                añosExperiencia);
        JOptionPane.showMessageDialog(this, "Técnico Creado");
        limpiarCajas();
        actualizarTablaTecnicos();
    }//GEN-LAST:event_btnCrearPersonaActionPerformed

    private void btnBuscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPersonaActionPerformed
        // TODO add your handling code here:
        String cedula = this.txtCedulaPersona.getText();
        Tecnico encontrado = this.miTaller.buscarTecnico(cedula);
        if (encontrado == null) {
            JOptionPane.showMessageDialog(this, "No existe");
        } else {
            this.txtNombrePersona.setText(encontrado.getNombre());
            this.txtTelefonoPersona.setText(encontrado.getTelefono());
            this.txtEspecialidadTecnico.setText(encontrado.getEspecializacion());
            this.txtExperienciaTecnico.setText("" + encontrado.getAñosExperiencia());
            actualizarTablaRelacionTecnicosCubiculos(cedula);
            actualizarTablaRelacionTecnicosCubiculos(cedula);
        }
    }//GEN-LAST:event_btnBuscarPersonaActionPerformed

    private void btnEditarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPersonaActionPerformed
        // TODO add your handling code here:
        String cedula = this.txtCedulaPersona.getText();
        Tecnico encontrado = this.miTaller.buscarTecnico(cedula);
        if (encontrado == null) {
            JOptionPane.showMessageDialog(this, "No existe");
        } else {
            String nombre = this.txtNombrePersona.getText();
            String telefono = this.txtTelefonoPersona.getText();
            int añosExperiencia = Integer.parseInt(this.txtExperienciaTecnico.getText());
            String especialidad = this.txtEspecialidadTecnico.getText();
            encontrado.setNombre(nombre);
            encontrado.setTelefono(telefono);
            encontrado.setAñosExperiencia(añosExperiencia);
            encontrado.setEspecializacion(especialidad);
            JOptionPane.showMessageDialog(this, "Actualizado");
            limpiarCajas();
        }
        actualizarTablaTecnicos();
        actualizarTablaRelacionTecnicosCubiculos(cedula);
    }//GEN-LAST:event_btnEditarPersonaActionPerformed

    private void btnEliminarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPersonaActionPerformed
        // TODO add your handling code here:
        String cedula = this.txtCedulaPersona.getText();
        Tecnico encontrado = this.miTaller.buscarTecnico(cedula);
        if (encontrado == null) {
            JOptionPane.showMessageDialog(this, "No existe");
        } else {
            this.miTaller.eliminarTecnico(encontrado);
            JOptionPane.showMessageDialog(this, "Eliminado");
            limpiarCajas();
        }
        actualizarTablaTecnicos();
        actualizarTablaRelacionTecnicosCubiculos(cedula);
    }//GEN-LAST:event_btnEliminarPersonaActionPerformed

    private void btnCrearCubiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCubiculoActionPerformed
        // TODO add your handling code here:
        String id = this.txtIdCubiculo.getText();
        String nombre = this.txtNombreCubiculo.getText();
        this.miTaller.crearCubiculo(id, nombre);
        JOptionPane.showMessageDialog(this, "Creado");
        limpiarCajas();
        actualizarComboCubiculos();
    }//GEN-LAST:event_btnCrearCubiculoActionPerformed

    private void btnAgregarRelacionCubiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRelacionCubiculoActionPerformed
        // TODO add your handling code here:
        String cedula = this.txtCedulaPersona.getText();

        Tecnico encontrado = this.miTaller.buscarTecnico(cedula);
        if (encontrado != null) {
            int indice = this.cbCubiculosTecnico.getSelectedIndex();
            Cubiculo seleccionado = this.miTaller.getMisCubiculos().get(indice);
            encontrado.getMisCubiculos().add(seleccionado);
            JOptionPane.showMessageDialog(this, "Asociado");
        }
        actualizarTablaRelacionTecnicosCubiculos(cedula);
    }//GEN-LAST:event_btnAgregarRelacionCubiculoActionPerformed

    private void btnEliminarRelacionCubiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarRelacionCubiculoActionPerformed
        // TODO add your handling code here:
        String cedula = this.txtCedulaPersona.getText();
        Tecnico encontrado = this.miTaller.buscarTecnico(cedula);
        if (encontrado != null) {
            int indice = this.cbCubiculosTecnico.getSelectedIndex();
            Cubiculo seleccionado = this.miTaller.getMisCubiculos().get(indice);
            encontrado.getMisCubiculos().remove(seleccionado);
            JOptionPane.showMessageDialog(this, "Desasociado");
        }
        actualizarTablaRelacionTecnicosCubiculos(cedula);
    }//GEN-LAST:event_btnEliminarRelacionCubiculoActionPerformed

    private void btnCertificadoTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCertificadoTecnicoActionPerformed
        // TODO add your handling code here:
        String contenido = "Esto es una prueba de certificado del taller " + this.miTaller.getNombre();
        guardarArchivo(contenido, "doc");
    }//GEN-LAST:event_btnCertificadoTecnicoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String contenido = "Nombre;Apellido;Nota\nFelipe;Buitrago;3.2\nLucas;Perez;5.0";
        guardarArchivo(contenido, "csv");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarRelacionCubiculo;
    private javax.swing.JButton btnBuscarPersona;
    private javax.swing.JButton btnCertificadoTecnico;
    private javax.swing.JButton btnCrearCubiculo;
    private javax.swing.JButton btnCrearPersona;
    private javax.swing.JButton btnEditarPersona;
    private javax.swing.JButton btnEliminarPersona;
    private javax.swing.JButton btnEliminarRelacionCubiculo;
    private javax.swing.JComboBox<String> cbCubiculosTecnico;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblRelacionTecnicoCubiculo;
    private javax.swing.JTable tblTecnicos;
    private javax.swing.JTextField txtCedulaPersona;
    private javax.swing.JTextField txtEspecialidadTecnico;
    private javax.swing.JTextField txtExperienciaTecnico;
    private javax.swing.JTextField txtIdCubiculo;
    private javax.swing.JTextField txtNombreCubiculo;
    private javax.swing.JTextField txtNombrePersona;
    private javax.swing.JTextField txtTelefonoPersona;
    // End of variables declaration//GEN-END:variables
}
